server:
  port: 6060
spring:
  datasource:
    username: root
    password: root
    url: jdbc:mysql://localhost:3306/oa?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    database: 0
    host: 127.0.0.1
    port: 6379
    password:
    # 连接池最大连接数（使用负值表示没有限制）
    # 连接池最大阻塞等待时间（使用负值表示没有限制）
    # 连接池中的最大空闲连接
    # 连接池中的最小空闲连接
    jedis:
      pool:
        max-active: 200
        max-wait: -1
        max-idle: 10
        min-idle: 0
    # 连接超时时间（毫秒）
    timeout: 1000
mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.demo.entity
  configuration:
    map-underscore-to-camel-case: true
